learning_log/learning_logs/urls.py
from django.urls import path, re_path
from . import views
# from django.conf.urls import url

app_name = 'learning_logs'

urlpatterns =[#主页
    path('', views.index, name='index'),
    #显示所有主题
    path('topics/', views.topics, name='topics'),

    re_path("topics/(?P<topic_id>\d+)/", views.topic, name='topic'),
    # 用于添加新主题网页
    path("new_topic/", views.new_topic, name='new_topic'),
    path("new_entry/(?P<topic_id>\d+)/", views.new_entry, name='new_entry'),
    path('edit_entry/(?P<entry>id>\d+/',views.edit_entry, name= 'edit_entry'),
]

learning_log/learning_logs/models.py
from django.db import models

class Topic(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.text
# Create your models here.
class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add = True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        if len(self.text)<50:
            return self.text
        else:
            return self.text[:50]+"..."

learning_log/learning_logs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import TopicForm, EntryForm
from .models import Topic, Entry

def index(request):
    return render(request,'learning_logs/index.html')
def topics(request):

    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)
def topic(request, topic_id):

	topic = Topic.objects.get(id=topic_id)
	entries = topic.entry_set.order_by('-date_added')
	context = {'topic': topic, 'entries': entries}
	return render(request, 'learning_logs/topic.html', context)


def new_topic(request):

    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(request.POST)
        if form.is_valid():
            form.save()
            # form.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))

    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

def new_entry(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))

    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

def edit_entry(request, entry_id):

    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = entry.topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))

    context = {'topic': topic, 'form': form, 'entry': entry}
    return render(request, 'learning_logs/edit_entry.html', context)

learning_log/learning_logs/templates/learning_logs/base.html
<p>
    <a href="{% url 'learning_logs:index' %}">Learning Log</a>-
     <a href="{% url 'learning_logs:topics' %}">Topics</a>
</p>

{% block content %}
<p>Alan</p>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% block content %}
<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
<p>Edit entry:</p>
 <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
{% csrf_token %}
{{ form.as_p }}<button name="submit">save changes</button>
</form>
{% endblock content %}

learning_log/learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}
{% block content %}
<p>Learning Log helps you keep track of your learning, for any topic you're
learning about.</p>
{% endblock content %}

learning_log/learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html"%}

{%block content%}
<p>Add a new entry:</p>
<form action = "{% url 'learning_logs:new_entry' topic.id %}" method = 'post'>
    {% csrf_token %}
    {{form.as_p}}
    <button name="submit">add entry </button>
</form>

{%endblock content%}

learning_log/learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html"%}

{%block content%}
<p>Add a new topic:</p>
<form action = "{% url 'learning_logs:new_topic'%}" method = 'post'>
    {% csrf_token %}
    {{form.as_p}}
    <button name="submit">add topic </button>
</form>

{%endblock content%}

learning_log/learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}
{% block content %}
<p>Topic: {{ topic }}</p>
<p>Entries:</p>
<ul>  {% for entry in entries %}
<li>
    <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
    <p>{{ entry.text|linebreaks }}</p>
    <p><a href="{% url 'learning_logs:edit_entry' entry.id %}"> edit_entry </a></p>
</li> {% empty %}

<li>
There are no entries for this topic yet.
</li>
{% endfor %}
</ul>
<a href="{% url 'learning_logs:new_entry' topic.id %}">Add a new entry:</a>
{% endblock content %}

learning_log/learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}
{% block content %}
<p>Topics</p>
<ul> {% for topic in topics %}
    <li>
        <a href ="{% url 'learning_logs:topic' topic.id%}">{{topic}}</a>
    </li>
    {% empty %}
<li>No topics have been added yet.</li>
    {% endfor %}  </ul>

<a href="{% url 'learning_logs:new_topic' %}">Add a new topic:</a>
{% endblock content %}